### ISSUE TITLE
Review part 2

### ISSUE THREAD

**Issue by matteodelucchi** [t4d-gmbh/git-and-its-remotes#13]
Overall review of part 2:

- [x] Remove Bitbucket from the pages table and add a list of many available hosts https://t4d-gmbh.github.io/using-git-in-academia/content/git-and-its-remotes/source/content/popular_remotes/index.html

**Comment by j-i-l** [comment]
Up to, including, "Remote Features" should be done now.

"Proj. Mgmt.", "Organizing Projs." are still 🚧 under construction, but soon ready.
