### ISSUE TITLE
Organizing projects and more

### ISSUE THREAD

**Issue by j-i-l** [t4d-gmbh/git-and-its-remotes#5]
https://github.com/t4d-gmbh/using-git-in-academia/blob/ffb0b0ca004ac04f2f4491d15d01b5ce4484418b/README.md?plain=1#L51-L53

> - Discover how remote services can be used to organize collaboration across repositories 
> - Basic understanding of GitHub's organisational structure (user, organizations, teams, projects, ...) 
> - Basic understanding of GitLab's organisational structure ([sub-]groups) 
---

# To Do

...todo

**Comment by matteodelucchi** [comment]
explain it with a simple example of a research group, with multiple members (incl. students), one project, multiple repos, and external collaborators.
@matteodelucchi : for Github
@j-i-l : for Gitlab
