### ISSUE TITLE
Examples and learning by doing

### ISSUE THREAD

**Issue by j-i-l** [t4d-gmbh/git-and-its-remotes#8]
https://github.com/t4d-gmbh/using-git-in-academia/blob/ffb0b0ca004ac04f2f4491d15d01b5ce4484418b/README.md?plain=1#L63-L64

> - Step through a "feature branch" development cycle by means of the project management tolls provided by the remote services 
> - Identify and resolve some conflicts directly on the remote service 

---

# To Do

...todo

**Comment by matteodelucchi** [comment]
- make similar exercise as in part 1 but all online in the remote IDE.
- continue the story from part 1 in the same exercise sheet, but with an other protagonist (with name starting with C) making its changes within a new feature branch and all online.
- make a bot who makes a commit when a pull/merge request is open (@j-i-l )
